titleOnly: true

scopes:
  - deps
  - vector
  - vector-agent
  - vector-aggregator
  - vector-shared

# Default
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
