# Including initContainers
## Values file for testing adding initContainers to Vector Pods.
initContainers:
  - name: sleep
    image: busybox
    command: ['sh', '-c', "sleep 5"]
  - name: wget
    image: busybox
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: data
      mountPath: "/vector-data-dir"

