{{- with .Values.secrets.generic }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vector.fullname" $ }}
  labels:
    {{- include "vector.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := $.Values.secrets.generic }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
