{{- if .Values.haproxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.haproxy.autoscaling.enabled }}
  replicas: {{ .Values.haproxy.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "haproxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.haproxy.rollWorkload }}
        checksum/config: {{ include (print $.Template.BasePath "/haproxy/configmap.yaml") . | sha256sum }}
      {{- end }}
      {{- with .Values.haproxy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "haproxy.selectorLabels" . | nindent 8 }}
      {{- with .Values.haproxy.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.haproxy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "haproxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.haproxy.podSecurityContext | nindent 8 }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: haproxy
          securityContext:
            {{- toYaml .Values.haproxy.securityContext | nindent 12 }}
          image: "{{ .Values.haproxy.image.repository }}:{{ .Values.haproxy.image.tag }}"
          imagePullPolicy: {{ .Values.haproxy.image.pullPolicy }}
          args:
            - -f
            - /usr/local/etc/haproxy/haproxy.cfg
          ports:
          {{- if not .Values.customConfig }}
            - name: stats
              containerPort: 1024
              protocol: TCP
          {{- end }}
          livenessProbe:
          readinessProbe:
          resources:
            {{- toYaml .Values.haproxy.resources | nindent 12 }}
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy
      volumes:
        - name: haproxy-config
          configMap:
            name: {{ if .Values.haproxy.existingConfigMap }}{{ .Values.haproxy.existingConfigMap }}{{ else }}{{ template "haproxy.fullname" . }}{{ end }}
      {{- with .Values.haproxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.haproxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.haproxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
