{{- if .Values.haproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
spec:
  ports:
{{- if not .Values.customConfig }}
    - name: stats
      port: 1024
      protocol: TCP
{{- end }}
{{- if or (eq .Values.role "Aggregator") (eq .Values.role "Stateless-Aggregator") }}
    - name: datadog-agent
      port: 8282
      protocol: TCP
    - name: fluent
      port: 24224
      protocol: TCP
    - name: logstash
      port: 5044
      protocol: TCP
    - name: splunk-hec
      port: 8080
      protocol: TCP
    - name: statsd
      port: 8125
      protocol: TCP
    - name: syslog
      port: 9000
      protocol: TCP
    - name: vector
      port: 6000
      protocol: TCP
{{- end }}
  {{- include "vector.ports" . | indent 4 }}
  selector:
    {{- include "haproxy.selectorLabels" . | nindent 4 }}
  type: {{ .Values.haproxy.service.type }}
{{- end }}
