{{- if (eq .Values.role "Agent") -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "vector.fullname" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vector.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vector.selectorLabels" . | nindent 8 }}
        vector.dev/exclude: "true"
    spec:
      {{- include "vector.pod" . | nindent 6 }}
{{- end }}
