{{- if (eq .Values.role "Aggregator") -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vector.fullname" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vector.selectorLabels" . | nindent 6 }}
  serviceName: {{ template "vector.fullname" . }}-headless
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vector.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "vector.pod" . | nindent 6 }}
  volumeClaimTemplates:
{{- if .Values.persistence.enabled }}
  - metadata:
      name: data
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- with .Values.persistence.selector }}
      selector:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
{{- end }}
